server:
  port: 8888
spring:
  application:
    name: iason-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/iasonenrollment/iason-config-repo
          clone-on-start: true
#          username: vbalaji215@gmail.com
#          password: Cognizant#1
          search-paths: '{application}'
logging:
  level:
    org:
      springframework:
        cloud: debug
        web: debug
